{% set name = "dirac-grid" %}
{% set version = "7r0p19" %}
{% set major = version.split('r')[0] %}
{% set minor = version.split('r')[1].split('p')[0] %}
{% set patch = version.split('p')[1] %}

package:
  name: {{ name|lower }}
  version: {{ major }}.{{ minor }}.{{ patch }}

source:
  url: https://github.com/DIRACGrid/DIRAC/archive/v{{ major }}r{{ minor }}p{{ patch }}.tar.gz
  sha256: b0dee0a9cbe6b13ffbddc19435353c8b898ed864203678ac17db916eea1df92c
  patches:
    - 0001-Patch-rootPath-to-be-CONDA_PREFIX.patch

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - mkdir -p ${PREFIX}/scripts
    - find ${PREFIX} -wholename '*/bin/*.py' -exec bash -c 'FN={} && NEW_FN=${PREFIX}/scripts/$(basename ${FN} .py) && cp ${FN} ${NEW_FN} && chmod +x ${NEW_FN}' \;

requirements:
  host:
    - python =2.7
    - pip
  run:
    - python =2.7
    - m2crypto # ==0.32
    - certifi
    - elasticsearch-dsl ~=6.3.1
    - funcsigs
    - future
    - futures
    - GitPython >=2.1.0
    - matplotlib-base >=2.1.0,<3.0
    - mysqlclient >=1.2.5
    - jinja2
    - numpy >=1.10.1
    - pexpect >=4.0.1
    - psutil >=4.2.0
    - pyasn1 >0.4.1
    - pyasn1-modules
    - pytz >=2015.7
    - requests >=2.9.1
    - simplejson >=3.8.1
    - six >=1.10
    - sqlalchemy >=1.0.9
    - stomp.py >=3.1.5
    - suds-jurko >=0.6
    - python-json-logger >=0.1.8
    - tornado >=5.0.0,<6.0.0
    - cmreshandler >1.0.0b4
    - rst2pdf >=0.93
    - multi-mechanize >=1.2.0
    - asn1
    - fts-rest
    - pyGSI

test:
  imports:
    - DIRAC
  commands:
    - dirac-jobexec.py --help
    - $CONDA_PREFIX/scripts/dirac-jobexec --help

about:
  home: http://diracgrid.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Distributed Infrastructure with Remote Agent Control
  description: |
    DIRAC (Distributed Infrastructure with Remote Agent Control) INTERWARE is a
    software framework for distributed computing providing a complete solution
    to one or more user community requiring access to distributed resources.
    DIRAC builds a layer between the users and the resources offering a common
    interface to a number of heterogeneous providers, integrating them in a
    seamless manner, providing interoperability, at the same time as an
    optimized, transparent and reliable usage of the resources.

    DIRAC has been started by the LHCb collaboration who still maintains it. It
    is now used by several communities (AKA VO=Virtual Organizations) for their
    distributed computing workflows.
  doc_url: https://dirac.readthedocs.io/
  dev_url: https://github.com/DIRACGrid/DIRAC

extra:
  recipe-maintainers:
    - chrisburr
